### ISSUE TITLE
Developer Doc TODO [Pls add on]

### ISSUE THREAD

**Issue by keenlok** [CS2103-AY1819S1-W14-2/main#64]
### **CONSISTENCY**
-  **Consistency** of cases for headings
- [ ] Title case for heading
- [ ] Sentence case for sub-headings
- [ ] Lead-in sentence/preface before a list with a colon, even a short and simple one is okay
- [ ] Make sure is a verb for instructions???
- [ ] All diagrams must be labeled, as long as there is **consistency**
- [ ] Should we change the layout of the doc for 2.1
- [ ] Reference to diagram so that developer knows that explaining the diagram
- [ ] Section 2.3 can be rewritten to not use numbering?
- [ ] The way the explanation is presented must be consistent: choose either bullet, numbering or prose and stick with it for everything... **CONSISTENCY**
- [ ] Section 2.6? Err... **CONSISTENCY**

- Section 3: its okay to not put the 3.1.1 in the table of contents...
